account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('password_validate/<uidb64>/<token>', views.password_validate, name='password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

from .views import AboutUsListView, ContactUsCreateView
from . import views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', AboutUsListView.as_view(), name="about"),
    path('contact_us/', ContactUsCreateView.as_view(), name="contact_us"),
    path('account/', include('account.urls'), name='account'),
    path('product/', include('product.urls'), name='product'),
    path('service/', include('service.urls'), name='service'),
    path('posts/', include('posts.urls'), name='posts'),
    path('checkout/', include('checkout.urls'), name='checkout'),
    path('pages/', include('pages.urls'), name='pages'),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),

]

handler404 = 'mywebsite.views.custom_page_not_found_view'
handler500 = 'mywebsite.views.custom_error_view'
handler403 = 'mywebsite.views.custom_permission_denied_view'
handler400 = 'mywebsite.views.custom_bad_request_view'


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    
admin.site.site_header = 'داشبورد نیک پاد محیط'
admin.site.site_title = 'نیک پاد محیط'
admin.site.index_title = 'مدیریت سایت'

pages/urls.py
from django.urls import path
from .views import CustomProductCreateView

app_name = 'pages'

urlpatterns = [
    path("custom_product/", CustomProductCreateView.as_view(), name="custom_product"),
]

posts/urls.py
from django.urls import path
from . import views
from .views import PostDetailView, PostListView

app_name = 'posts'
urlpatterns = [
    path("", PostListView.as_view(), name="index"),
    path("<slug>/", PostDetailView.as_view(), name="detail"),
]

product/urls.py
from django.urls import path
from .views import ProductCreateView, ProductDetailView, ProductUpdateView, CategoryDetailView, ProductCategoryListView
from . import views

app_name = 'product'
urlpatterns = [
    path("categories/", ProductCategoryListView.as_view(), name="index"),
    path("category/<slug>/", CategoryDetailView.as_view(), name="category_detail"),
    path('create/', ProductCreateView.as_view(), name="create"),
    path('<slug:slug>/update/', ProductUpdateView.as_view(), name="update"),
    path('search/', views.search_view, name="search"),
    path('<slug>/', ProductDetailView.as_view(), name="detail"),
]

service/urls.py
from django.urls import path
from . import views
from .views import CategoryServiceListView, ServiceDetailView, CategoryServiceDetailView

app_name = 'service'
urlpatterns = [
    # path("", ServiceListView.as_view(), name="service_list"),
    path("", CategoryServiceListView.as_view(), name="service_list"),
    path("<slug>/", CategoryServiceDetailView.as_view(), name="category_detail"),
    path("detail/<slug>/", ServiceDetailView.as_view(), name="detail"),
]

templates/includes/footer.html
{% load static %}

<!-- Footer Start -->
<div class="bg-white" style="margin-top: auto;">
    <div class="container">
        <div class="container">
            <footer class="py-5">
                <div class="row">
                    <div class="col-6 col-md-2 mb-3">
                        <h5>دسترسی سریع</h5>
                        <ul class="nav flex-column">
                            <li class="nav-item mb-2"><a href="{% url 'index' %}" class="nav-link p-0 text-body-secondary">صفحه
                                    اصلی</a>
                            </li>
                            <li class="nav-item mb-2"><a href="{% url 'product:index' %}"
                                    class="nav-link p-0 text-body-secondary">محصولات</a>
                            </li>
                            <li class="nav-item mb-2"><a href="{% url 'checkout:cart' %}" class="nav-link p-0 text-body-secondary">سبد
                                    خرید</a>
                            </li>
                            <li class="nav-item mb-2"><a href="{% url 'posts:index' %}" class="nav-link p-0 text-body-secondary">
                                    مقالات</a>
                            </li>
                            <li class="nav-item mb-2"><a href="{% url 'about' %}" class="nav-link p-0 text-body-secondary">درباه
                                    ما</a></li>
                            <li class="nav-item mb-2"><a href="{% url 'contact_us' %}" class="nav-link p-0 text-body-secondary">ارتباط با
                                    ما</a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-6 col-md-3 mb-3">
                        <h5>ما را دنبال کنید</h5>
                        <ul class="nav ">
                            <li class="nav-item mb-2">

                                <a class="btn btn-outline-primary my-1 me-1" href="https:\\facebook.com/profile.php?id=100093201273836" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-facebook"
                                        viewBox="0 0 16 16">
                                        <path
                                            d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
                                    </svg></a>
                                <a class="btn btn-outline-danger my-1 me-1" href="https://www.instagram.com/nikpadmohit/" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-instagram"
                                        viewBox="0 0 16 16">
                                        <path
                                            d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
                                    </svg></a>
                                <a class="btn btn-outline-danger my-1 me-1" href=""><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-youtube"
                                        viewBox="0 0 16 16">
                                        <path
                                            d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z" />
                                    </svg></a>
                                <a class="btn btn-outline-info my-1 me-1 " href="https:\\linkedin.com/in/nik-pad-mohit-15090b278" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-linkedin"
                                        viewBox="0 0 16 16">
                                        <path
                                            d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z" />
                                    </svg></a>
                                <a class="btn btn-outline-primary my-1 me-1" href=""><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-telegram"
                                        viewBox="0 0 16 16">
                                        <path
                                            d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z" />
                                    </svg></a>
                            </li>

                        </ul>
                    </div>

                    <div class="col-md-5 offset-md-1 mb-3">
                        <form action="{% url 'newsletter:subscribe' %}" method="POST">
                            {% csrf_token %}
                            <h5>برای دریافت خبرهای سایت عضو شوید</h5>
                            <p>تازه‌های مرتبط با فعالیت ما هر ماه با شما به اشتراک گذاشته می‌شود. </p>
                            <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                                <input name="email" required dir="ltr" id="newsletter1" type="email" class="form-control" placeholder="آدرس ایمیل">
                                <button class="btn btn-success" type="submit">عضویت</button>
                            </div>
                        </form>
                    </div>
                </div>

            </footer>
        </div>    
    </div>
</div>
<!-- Footer End -->

<!-- Footer Bottom Start -->

<!-- Footer Bottom End -->

templates/includes/message.html
{% if messages %}
<div class="w-100">

        {% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{message.tags}} {% endif %} alert-dismissible fade show" role="alert">
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
            <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}

</div>
{% endif %}

templates/includes/navbar.html
{% load static %}
<!-- Top bar Start -->
<div class="top-bar bg-dark text-white bg-opacity-50">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                ۰۹۹۱۱۲۸۷۸۰۵
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-telephone-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                        d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z" />
                </svg>
            </div>
            <div class="col-sm-6">
                npmohit@gmail.com
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-envelope-fill" viewBox="0 0 16 16">
                    <path
                        d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z" />
                </svg>
            </div>
        </div>
    </div>
</div>
<!-- Top bar End -->

<!-- Nav Bar Start -->
<nav class="navbar navbar-expand-lg navbar-dark bg-success py-0">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent2"
            aria-controls="navbarSupportedContent2" aria-expanded="false" aria-label="تبديل التنقل">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent2">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">صفحه اصلی</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'product:index' %}">محصولات</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'pages:custom_product' %}">
                        درخواست محصول جدید</a>
                </li>  
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'service:service_list' %}">خدمات</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'posts:index' %}">مقالات</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'about' %}">درباره ما</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'contact_us' %}" tabindex="-1" aria-disabled="true">تماس
                        با ما</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown bg-success">
                    <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown2" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        {{ request.user }}
                    </a>
                    <ul class="dropdown-menu mt-0" aria-labelledby="navbarDropdown2">
                        <li><a class="dropdown-item" href="{% url 'account:logout' %}"><svg
                                    xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-chevron-left" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                        d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" />
                                </svg> خروج </a></li>
                        <li><a class="dropdown-item" href="{% url 'account:profile' %}"><svg
                                    xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-chevron-left" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                        d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" />
                                </svg> پروفایل</a></li>
                        <li><a class="dropdown-item" href="{% url 'checkout:orders' %}"><svg
                                    xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-chevron-left" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                        d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" />
                                </svg> سفارشات</a></li>
                    </ul>
                </li>
                <li title="خروج" class="nav-item"><a class="nav-link active" href="{% url 'account:logout' %}"><svg
                            xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                            class="bi bi-power" viewBox="0 0 16 16">
                            <path d="M7.5 1v7h1V1h-1z" />
                            <path
                                d="M3 8.812a4.999 4.999 0 0 1 2.578-4.375l-.485-.874A6 6 0 1 0 11 3.616l-.501.865A5 5 0 1 1 3 8.812z" />
                        </svg></a></li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'account:login' %}">ورود</a>
                </li>
                <li class="nav-item">

                    <a class="nav-link active" id="nav_separator" aria-current="page" href="#">|</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'account:register' %}">ثبت نام</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- Nav Bar End -->

<!-- Bottom Bar Start -->
<div class="container-fluid  py-2 bg-white">
    <div class="bottom-bar">
        <!-- <div class="container-fluid"> -->
        <div class="row align-items-center">
            <div class="col-md-3  text-center my-1">
                <div class="logo">
                    <a class="h3" href="{% url 'index' %}" role="banner" style="text-decoration: none;">
                        <img src="{% static 'img/nmpohit_logo.png' %}" alt="Logo">
                        نیک پاد محیط
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="search">
                    <form action="{% url 'product:search' %}" class="d-flex">
                        <input class="form-control" name="q" type="search" placeholder="جستجو" aria-label="Search"
                            required>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-search" viewBox="0 0 16 16">
                            <path
                                d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                        </svg>
                    </form>
                </div>
            </div>
            <div class="col-md-3 text-center mt-2">

                <a href="{% url 'checkout:cart' %}" type="button"
                    class="btn btn-outline-danger position-relative px-5 ">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                        class="bi bi-cart4" viewBox="0 0 16 16">
                        <path
                            d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z" />
                    </svg>
                    <span class="position-absolute top-0 start-0 translate-middle badge bg-danger">
                        {{ cart_count }}
                    </span>
                </a>
            </div>
        </div>
        <!-- </div> -->
    </div>
</div>
<!-- Bottom Bar End -->