checkout/urls.py
from django.urls import path
from . import views

app_name = 'checkout'
urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path("shipping/", views.shipping, name="shipping"),
    path("place_order/", views.place_order, name="place_order"),
    path("orders/", views.orders, name="orders"),
    path("orders/cancel/<int:order_id>", views.cancel, name="cancel"),
    path("payment/<int:order_id>", views.payment, name="payment"),
    path("add_to_cart/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path("increase_quantity/<int:product_id>/", views.increase_quantity, name="increase_quantity"),
    path("decrease_quantity/<int:product_id>/", views.decrease_quantity, name="decrease_quantity"),
    path('remove_from_cart/<int:product_id>/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart')
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

from .views import AboutUsListView, ContactUsCreateView
from . import views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', AboutUsListView.as_view(), name="about"),
    path('contact_us/', ContactUsCreateView.as_view(), name="contact_us"),
    path('account/', include('account.urls'), name='account'),
    path('product/', include('product.urls'), name='product'),
    path('service/', include('service.urls'), name='service'),
    path('posts/', include('posts.urls'), name='posts'),
    path('checkout/', include('checkout.urls'), name='checkout'),
    path('pages/', include('pages.urls'), name='pages'),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),

]

handler404 = 'mywebsite.views.custom_page_not_found_view'
handler500 = 'mywebsite.views.custom_error_view'
handler403 = 'mywebsite.views.custom_permission_denied_view'
handler400 = 'mywebsite.views.custom_bad_request_view'


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    
admin.site.site_header = 'داشبورد نیک پاد محیط'
admin.site.site_title = 'نیک پاد محیط'
admin.site.index_title = 'مدیریت سایت'

pages/urls.py
from django.urls import path
from .views import CustomProductCreateView

app_name = 'pages'

urlpatterns = [
    path("custom_product/", CustomProductCreateView.as_view(), name="custom_product"),
]

product/urls.py
from django.urls import path
from .views import ProductCreateView, ProductDetailView, ProductUpdateView, CategoryDetailView, ProductCategoryListView
from . import views

app_name = 'product'
urlpatterns = [
    path("categories/", ProductCategoryListView.as_view(), name="index"),
    path("category/<slug>/", CategoryDetailView.as_view(), name="category_detail"),
    path('create/', ProductCreateView.as_view(), name="create"),
    path('<slug:slug>/update/', ProductUpdateView.as_view(), name="update"),
    path('search/', views.search_view, name="search"),
    path('<slug>/', ProductDetailView.as_view(), name="detail"),
]

product/models.py
from django.db import models
from django.urls import reverse
from .storage import ProtectedMedia
from django.utils.translation import gettext as _


# Create your models here.
class Category(models.Model):
    title = models.CharField(_("عنوان"), max_length=150)
    description = models.TextField(_("توضیحات"))
    slug = models.SlugField(_("اسلاگ"),allow_unicode=True)
    image = models.ImageField(_("تصویر"), upload_to='category/image', height_field=None, width_field=None, max_length=None) 
    timestamp = models.DateTimeField(_("تاریخ ثبت"), auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(_("تاریخ به روزرسانی"), auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("product:category_detail", args={self.slug})    
    
    class Meta:
        verbose_name = 'دسته‌بندی'
        verbose_name_plural = 'دسته‌بندی‌ها'        
    

    def download_media(instance, filename):
        return "%s/%s"%(instance.slug, filename)


class Product(models.Model):
    user = models.ForeignKey("account.User", verbose_name=_("کاربر"), on_delete=models.CASCADE)
    title = models.CharField(_("عنوان"), max_length=150)
    category = models.ForeignKey(Category , verbose_name=_("دسته‌بندی"), on_delete=models.CASCADE)
    slug = models.SlugField(_("اسلاگ"), unique=True , allow_unicode=True)
    image = models.ImageField(_("تصویر"), upload_to='product/image', null=True, blank=True)
    media = models.FileField(_("رسانه"), upload_to='download_media', storage=ProtectedMedia, null=True, blank=True)
    description = models.TextField(_("توضیحات"), null=True, blank=True)
    price = models.IntegerField(_("قیمت"))
    unit = models.CharField(_("واحد"), max_length=150)
    featured = models.BooleanField(_("محصول ویژه؟"), default=False)
    recent_product = models.BooleanField(_("محصول جدید؟"), default=False)
    available = models.BooleanField(_("موجود است؟"))

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("product:detail", args={self.slug})
    
    class Meta:
        verbose_name_plural = "محصولات"
        verbose_name = "محصول"
    
class Specifications(models.Model):
    product = models.ForeignKey(Product, verbose_name=_("محصول"), on_delete=models.CASCADE)
    title = models.CharField(_("مشخصه"), max_length=50)
    description = models.CharField(_("توضیحات"), max_length=50)

    class Meta:
        verbose_name_plural = "مشخصات محصول"
        verbose_name = "مشخصه "   


     
 

product/forms.py
from django.forms import ModelForm
from django import forms
from .models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        # fields = "__all__"
        fields = [
            'title',
            'slug',
            'category',
            'image',
            'media',
            'description',
            'price',
            'featured',
            'recent_product',
        ]  
        def clean_field(self):
            description = self.cleaned_data["description"]
            if len(description) < 6:
                raise forms.validationError("The description is too short")              

product/views.py
from django.http import HttpResponse
from django.shortcuts import render
from itertools import chain
from django.views.generic.edit import CreateView, UpdateView
from .models import Product, Category
from .forms import ProductForm
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.db.models import Q
from django.core.paginator import Paginator
from checkout.models import CartItem
from checkout.views import cart_id


# Create your views here.
class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/create_view.html'
    success_url = '/'

class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/update_view.html'
    success_url = '/'


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product/detail.html'
    context_object_name = 'product'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        related_products = Product.objects.filter(category=product.category).exclude(slug=product.slug)
        # is_in_cart = CartItem.objects.all().filter(cart__cart_id=cart_id(self.request), product=product).exists()
        context["related_products"] = related_products
        # context["is_in_cart"] = is_in_cart
        return context

def search_view(request, *args, **kwargs):
    try:
        q = request.GET.get('q',)
    except:
        q = False
    if q== None:
        return render(request, 'product/search_result.html')        
    obj = Product.objects.filter(Q(title__icontains=q) | Q(description__icontains=q) | Q(category__title__icontains=q))
    results = list(chain(obj))
    paginator = Paginator(results, 1)
    page = request.GET.get('page')
    page_products = paginator.get_page(page)
    context = {
        'results': page_products,
        'obj': obj,
        'q': q
    }
    return render(request, 'product/search_result.html', context)


class ProductCategoryListView(ListView):
    template_name = 'product/category_list.html'
    model = Category
    paginate_by = 5

    

class CategoryDetailView(DetailView):
    model = Category

    template_name = 'product/category_detail.html'
    
    def get_context_data(self, **kwargs):
        id = self.get_object().id
        context = super().get_context_data(**kwargs)
        context["products"] =  Product.objects.filter(category__pk=id)
        return context    


    
    

templates/product/category_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}{% endblock %}

{% block content %}

{% if products %}
<section>
    <div class="container py-5">
      <div class="row justify-content-center mb-3">
        {% for product in products %}
        <div class="col-md-12 col-xl-10 mb-2">
          <div class="card shadow-0 border rounded-3">
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0">
                  <div class="bg-image hover-zoom ripple rounded ripple-surface">
                    <img src="{{ product.image.url }}"
                      class="w-100" />
                    <a href="{% url 'product:detail' product.slug %}">
                      <div class="hover-overlay">
                        <div class="mask" style="background-color: rgba(253, 253, 253, 0.15);"></div>
                      </div>
                    </a>
                  </div>
                </div>
                <div class="col-md-6 col-lg-6 col-xl-6">
                  <h5>{{ product.title }}</h5>
                  {% for item in product.specifications_set.all %}
                  <p class="text-truncate mb-4 mb-md-0">
                        <span class="badge bg-secondary">{{ item.title }}</span>
                        <span>{{ item.description }}</span>
                    </p>
                    {% endfor %}
                </div>
                <div class="col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start">

                  <span class="text-danger">{{ product.price|intcomma:False }} <span class="px-2">تومان</span></span>
                  <div class="d-flex flex-column mt-4">
                    {% if product.available %}
                    <a href="{% url 'checkout:add_to_cart' product.id %}" class="btn btn-danger">افزودن به سبد خرید</a>
                    {% else %}
                    <a href="#" class="btn btn-danger btn-sm disabled">ناموجود</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
</section>
{% endif %}


<p class="products h4 p-3 text-center  mt-5" style="background-image: linear-gradient(rgb(210, 244, 234), rgb(243, 246, 255, 1));
  "> 
  {{ object.title }}
</p>
<div class="container mt-5">
    {% if products %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for product in products %}
        <div class="col">
            <a class="nav-link" href="{% url 'product:detail' product.slug %}">
                <div class="card h-100">
                    <div class="card-header bg-transparent border-success">{{ product.title }}</div>

                    <img src="{{ product.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body text-end">
                        <h6 class="card-title">{{ product.price}} تومان</h6>
                    </div>
                    <div class="card-footer"> 

                    </div>
                </div>
            </a>
        </div>
        {% endfor %}        
    </div>
    {% else %}
    <div class="text-center m-4">
        <p class="h3">در این دسته‌بندی محصولی تعریف نشده است.</p>
        <a href="{% url 'admin:login' %}">
            <button class="btn btn-outline-success px-5 mt-5 rounded-pill">  اضافه کردن محصول جدید </button>
        </a>
    </div>       
    {% endif %}
</div>


{% endblock %}

templates/product/category_list.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}

  {% if object_list %}
  <section style="background-color: #eee;">
    <div class="container py-5">
      <div class="row d-flex justify-content-center mb-3">
        <div class="col-md-12 col-xl-10">
            {% for item in object_list %}
            <a href="{{ item.get_absolute_url}}">
          <div class="card shadow-0 border rounded-3 mb-2">
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0">
                  <div class="bg-image hover-zoom ripple rounded ripple-surface">
                    <img src="{{ item.image.url }}"
                      class="w-100" />
                    <a href="#!">
                      <div class="hover-overlay">
                        <div class="mask" style="background-color: rgba(253, 253, 253, 0.15);"></div>
                      </div>
                    </a>
                  </div>
                </div>
                <div class="col-md-6 col-lg-6 col-xl-6">
                  <h5><span class="text-danger">دسته‌بندی: </span> {{ item.title }}</h5>

                  <p class="text-truncate">
                    محصولات:
                  </p>
                    {% for item in item.product_set.all %}
                      <a class="btn btn-sm btn-success mb-1" href="{% url 'product:detail' item.slug %}">{{ item.title }}</a>
                    {% endfor %}
                </div>
                <div class="col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start">

                  {% comment %} <h6 class="text-success">ارسال رایگان</h6> {% endcomment %}
                  <div class="d-flex flex-column mt-4">
                    <a href="{% url 'product:category_detail' item.slug %}" class="btn btn-danger btn-sm">مشاهده همه محصولات گروه</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
  {% else %}
  <div class="text-center m-4">
    <p class="h3">دسته‌بندی محصولات خالی است.</p>
    <a href="{% url 'admin:login' %}">
        <button class="btn btn-outline-success px-5 mt-5 rounded-pill">  ایجاد دسته‌بندی محصولات </button>
    </a>
</div>
  {% endif %}



<!-- Category Start-->

<!-- Category End-->

{% endblock %}

templates/product/create_view.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit">
    </form>

{% endblock  %}

templates/product/detail.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}

{% load static %}
{% load humanize %}

<section style="background-color: #eee;">
    <div class="container py-5">
      <div class="row justify-content-center mb-3">
        <div class="col-md-12 col-xl-10">
          <div class="card shadow-0 border rounded-3">
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0">
                  <div class="bg-image hover-zoom ripple rounded ripple-surface">
                    <img src="{{ product.image.url }}"
                      class="w-100" />
                    <a href="#!">
                      <div class="hover-overlay">
                        <div class="mask" style="background-color: rgba(253, 253, 253, 0.15);"></div>
                      </div>
                    </a>
                  </div>
                </div>
                <div class="col-md-6 col-lg-6 col-xl-6">
                  <h5>{{ product.title }}</h5>

                  <p class="text-truncate mb-4 mb-md-0">
                    {{ product.description }}
                  </p>
                  {% for item in product.specifications_set.all %}
                  <p class="text-truncate mb-4 mb-md-0">
                        <span class="badge bg-secondary">{{ item.title }}</span>
                        <span>{{ item.description }}</span>
                    </p>
                    {% endfor %}
                </div>
                <div class="col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start">

                  <span class="text-danger">{{ product.price|intcomma:False }} <span class="px-2">تومان</span></span>
                  <div class="d-flex flex-column mt-4">
                    {% if product.available %}
                    <a href="{% url 'checkout:add_to_cart' product.id %}" class="btn btn-danger">افزودن به سبد خرید</a>
                    {% else %}
                    <a href="#" class="btn btn-danger btn-sm disabled">ناموجود</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>



  {% endblock %}

templates/product/search_result.html
{% extends 'base.html' %}

{% block content %}




        <p class="products h4 p-3 text-center  mt-5" style="background-image: linear-gradient(rgb(210, 244, 234), rgb(243, 246, 255, 1));
        ">نتایج جستجوی عبارت : {{q}}</p>
        
        <div class="container">
        {% if results %}
        <div class="row row-cols-1 row-cols-md-3 g-4">
          {% for item in results %}
          <div class="col">
            <a class="nav-link" href="{{ item.get_absolute_url}}">
              <div class="card">
                <img src="{{ item.image.url }}" class="card-img-top" alt="...">
      
                <div class="card-footer text-center">
                  <small class="h5 text-body-secondary">{{ item.title }}</small>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
        </div>
            <!-- Pagination Start -->
            <div class="col-md-12">
                <nav aria-label="Page navigation example">
                    {% if results.has_other_pages %}
                    <ul class="pagination justify-content-center">
                        {% if results.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ results.previous_page_number }}" tabindex="-1">Previous</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">Previous</a>
                        </li>                            
                        {% endif %}
                        {% for x in results.paginator.page_range %}
                        {% if results.number == x %}
                        <li class="page-item active disabled"><a class="page-link" href="?page={{ x }}">{{ x }}</a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ x }}">{{ x }}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if results.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ results.next_page_number }}">Next</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">Next</a>
                        </li>                            
                        {% endif %}
                    </ul>
                    {% endif %}
                </nav>
            </div>
            <!-- Pagination Start -->        
        {% else %}
        <div class="text-center m-4">
          <p class="h3">نتیجه‌ای یافت نشد!</p>
      </div>
        {% endif %}
      </div>
      


<!-- Product List End -->

{% endblock %}

templates/product/update_view.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Save">
    </form>

{% endblock  %}