checkout/urls.py
from django.urls import path
from . import views

app_name = 'checkout'
urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path("shipping/", views.shipping, name="shipping"),
    path("place_order/", views.place_order, name="place_order"),
    path("orders/", views.orders, name="orders"),
    path("orders/cancel/<int:order_id>", views.cancel, name="cancel"),
    path("payment/<int:order_id>", views.payment, name="payment"),
    path("add_to_cart/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path("increase_quantity/<int:product_id>/", views.increase_quantity, name="increase_quantity"),
    path("decrease_quantity/<int:product_id>/", views.decrease_quantity, name="decrease_quantity"),
    path('remove_from_cart/<int:product_id>/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart')
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

from .views import AboutUsListView, ContactUsCreateView
from . import views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', AboutUsListView.as_view(), name="about"),
    path('contact_us/', ContactUsCreateView.as_view(), name="contact_us"),
    path('account/', include('account.urls'), name='account'),
    path('product/', include('product.urls'), name='product'),
    path('service/', include('service.urls'), name='service'),
    path('posts/', include('posts.urls'), name='posts'),
    path('checkout/', include('checkout.urls'), name='checkout'),
    path('pages/', include('pages.urls'), name='pages'),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),

]

handler404 = 'mywebsite.views.custom_page_not_found_view'
handler500 = 'mywebsite.views.custom_error_view'
handler403 = 'mywebsite.views.custom_permission_denied_view'
handler400 = 'mywebsite.views.custom_bad_request_view'


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    
admin.site.site_header = 'داشبورد نیک پاد محیط'
admin.site.site_title = 'نیک پاد محیط'
admin.site.index_title = 'مدیریت سایت'

pages/urls.py
from django.urls import path
from .views import CustomProductCreateView

app_name = 'pages'

urlpatterns = [
    path("custom_product/", CustomProductCreateView.as_view(), name="custom_product"),
]

product/urls.py
from django.urls import path
from .views import ProductCreateView, ProductDetailView, ProductUpdateView, CategoryDetailView, ProductCategoryListView
from . import views

app_name = 'product'
urlpatterns = [
    path("categories/", ProductCategoryListView.as_view(), name="index"),
    path("category/<slug>/", CategoryDetailView.as_view(), name="category_detail"),
    path('create/', ProductCreateView.as_view(), name="create"),
    path('<slug:slug>/update/', ProductUpdateView.as_view(), name="update"),
    path('search/', views.search_view, name="search"),
    path('<slug>/', ProductDetailView.as_view(), name="detail"),
]

checkout/models.py
from django.db import models
from account.models import User
from django.utils.translation import gettext as _
from product.models import Product
from enum import Enum


class Cart(models.Model):
    cart_id = models.CharField(_("شناسه"), max_length=50)
    is_active = models.BooleanField(_("فعال؟"), default=True)
    date_added = models.DateTimeField(_("تاریخ ثبت"), auto_now=False, auto_now_add=True)
    user = models.ForeignKey(User, verbose_name=_("کاربر"), on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.cart_id
    
    class Meta:
        verbose_name_plural = "سبدهای خرید"
        verbose_name = "سبد خرید"    
    
class CartItem(models.Model):
    product = models.ForeignKey(Product, verbose_name=_("محصول"), on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, verbose_name=_("سبد"), on_delete=models.CASCADE)
    quantity = models.IntegerField(_("مقدار"))
    is_active = models.BooleanField(_("فعال؟"), default=True)

    def __str__(self):
        return self.product.title
    
    class Meta:
        verbose_name_plural = "اقلام خرید"
        verbose_name = "قلم"  

class PaymentStatus(Enum):
    PENDING= 'در دست بررسی'
    APPROVED = 'تایید شده'
    REJECTED = 'رد شده'

class Payment(models.Model):
    PAYMENT_STATUS_CHOICES  = (
        ('PENDING', 'در دست بررسی'),
        ('APPROVED', 'تایید شده'),
        ('REJECTED', 'رد شده'),
    )       
    user = models.ForeignKey(User, verbose_name=_("کاربر"), on_delete=models.CASCADE)
    order_id = models.ForeignKey("checkout.Order", verbose_name=_("سفارش"), on_delete=models.CASCADE)
    recipe_image = models.ImageField(_("تصویر رسید پرداخت"), upload_to='payment/image', height_field=None, width_field=None, max_length=None) 
    status = models.CharField(_("وضعیت"), max_length=50, choices=PAYMENT_STATUS_CHOICES, default='PENDING')
    created_at = models.DateTimeField(_("تاریخ ثبت"), auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.status
    
    class Meta:
        verbose_name_plural = "پرداخت‌ها"
        verbose_name = "پرداخت"  

class Order(models.Model):
    ORDER_STATUS_CHOICES  = (
        ('New', 'جدید'),
        ('Accepted', 'پذیرفته شده'),
        ('Completed', 'تکمیل شده'),
        ('Cancelled', 'لغو شده')
    )
    user = models.ForeignKey(User, verbose_name=_("کاربر"), on_delete=models.SET_NULL, null=True)
    order_number = models.CharField(_("شماره سفارش"), max_length=20)
    payment_status = models.BooleanField(_("پرداخت شده"), default=False)
    shipping_status = models.BooleanField(_("ارسال شده"), default=False)
    first_name = models.CharField(_("نام"), max_length=100)
    last_name = models.CharField(_("نام خانوادگی"), max_length=100)
    phone_number = models.CharField(_("تلفن"), max_length=20)
    email = models.EmailField(_("ایمیل"), max_length=254)
    state = models.CharField(_("استان"), max_length=50)
    city = models.CharField(_("شهر"), max_length=100)
    shipping_address = models.TextField(_("آدرس گیرنده"), max_length=100)
    zip_code = models.CharField(_("کد پستی"), max_length=250)
    status = models.BooleanField(_("تایید شده"), max_length=50, default=False)
    total = models.DecimalField(_("جمع کل"), max_digits=10, decimal_places=2, default=0.00)
    total_amount = models.DecimalField(_("پرداخت"), max_digits=10, decimal_places=2, default=0.00)
    created_at = models.DateTimeField(_("تاریخ ثبت"), auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(_("تاریخ به روزرسانی"), auto_now=True, auto_now_add=False)


    def __str__(self):
        return f"سفارش #{self.pk} - {self.first_name} { self.last_name}"    
    
    class Meta:
        verbose_name_plural = "سفارشات"
        verbose_name = "سفارش"    
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name=_("سفارش"), on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, verbose_name=_("محصول"), on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(_("مقدار"))
    price = models.DecimalField(_("قیمت"), max_digits=10, decimal_places=0)

    def __str__(self):
        return self.product.title
    
    class Meta:
        verbose_name_plural = "اقلام سفارشات"
        verbose_name = "قلم سفارش"  

checkout/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from product.models import Product
from .forms import OrderForm, PaymentForm
from .models import Order
from .models import Cart, CartItem, Order, OrderItem, Payment
from decimal import Decimal
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse
import datetime
from django.core.files.storage import FileSystemStorage
import os
from django.conf import settings


def cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


@login_required
def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(user = request.user, is_active=True)
    except Cart.DoesNotExist:
        cart = Cart.objects.create(user=request.user, cart_id = cart_id(request))
    cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart = cart)
        cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart = cart)
        cart_item.save()

    return redirect('checkout:cart')


@login_required
def increase_quantity(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = get_object_or_404(Cart, user=request.user, is_active=True)
    cart_item = get_object_or_404(CartItem, product=product, cart = cart)
    cart_item.quantity += 1
    cart_item.save()

    return redirect('checkout:cart')


@login_required
def decrease_quantity(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = get_object_or_404(Cart, user=request.user, is_active=True)
    cart_item = get_object_or_404(CartItem, product=product, cart = cart)
    cart_item.quantity -= 1
    cart_item.save()

    return redirect('checkout:cart')


@login_required
def remove_from_cart(request, product_id, cart_item_id):
    cart = get_object_or_404(Cart, user = request.user, is_active=True)
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('checkout:cart')


@login_required
def cart(request, cart_items = None, total = 0):
    try:
        tax = 0
        grand_total = 0
        cart = Cart.objects.get(user = request.user, is_active=True)        
        cart_items = CartItem.objects.filter(cart=cart, is_active = True)
        for item in cart_items:
            total += item.product.price * item.quantity
        tax_rate = Decimal(0.09)
        tax = (total*tax_rate)
        tax = Decimal("%.2f" %(tax))
        grand_total = total + tax   
    except ObjectDoesNotExist:
        pass
    context = {
        'cart_items': cart_items,
        'total': total,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'checkout/cart.html', context)


@login_required
def shipping(request, cart_items = None, total = 0):

    form = OrderForm()

    try:
        cart = Cart.objects.get(user = request.user, is_active=True)        
        cart_items = CartItem.objects.filter(cart=cart, is_active = True)
        for item in cart_items:
            total += item.product.price * item.quantity
        # address = Address.objects.filter(user = request.user).first()
    except ObjectDoesNotExist:
        return HttpResponse('Error')
    context = {
        'cart_items': cart_items,
        'total': total,
        'form': form,
        # 'exist_address': exist_address
    }
    return render(request, 'checkout/shipping.html', context)


@login_required
def place_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            # Calculate total amount (assuming you have a cart or order items logic)
            total_amount = 0  # Your own implementation
            order_number = 0

            # Create the order
            order = Order(
                state=form.cleaned_data['state'],
                city=form.cleaned_data['city'],
                shipping_address=form.cleaned_data['shipping_address'],
                zip_code=form.cleaned_data['zip_code'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                phone_number=form.cleaned_data['phone_number'],
                email=form.cleaned_data['email'],
                total_amount=total_amount,
                order_number = order_number,
                user = request.user
            )
            order.save()

            # Process the cart items
            cart = Cart.objects.get(user = request.user)  # request.session.get('cart', {})
            cart_items = CartItem.objects.filter(cart=cart)
            for item in cart_items:
                product = Product.objects.get(pk=item.product.id)
                price = product.price * item.quantity
                total_amount += price * item.quantity

                # Create an order item
                order_item = OrderItem(
                    order=order,
                    product=product,
                    quantity=item.quantity,
                    price=price
                )
                order_item.save()

            # Update the total amount of the order
            order.total_amount = total_amount

            # Update the order number of the order
            yr = int(datetime.date.today().strftime('%Y'))
            mt = int(datetime.date.today().strftime('%m'))
            dt = int(datetime.date.today().strftime('%d'))
            d = datetime.date(yr,mt,dt)
            current_date = d.strftime('%Y%m%d')
            order_number = current_date + str(order.id)
            order.order_number = order_number            
            order.save()
            cart.delete()
            # cart.is_active = False
            # cart.save()

            # Redirect to a confirmation page
            # return redirect('order_confirmation', order_id=order.pk)
            return redirect('checkout:orders')
            # return render(request, 'checkout:payment', {'order_id': order.pk})
        else:
            return HttpResponse(form.errors)
    else:
        pass

    return render(request, 'checkout:shipping')

login_required
def payment(request, order_id):
    if request.method == 'POST':
        order = Order.objects.get(user=request.user, id=order_id)
        order_number = order.order_number
        image = request.FILES['recipe']
        fs = FileSystemStorage()
        # Generate a new file name

        folder = settings.MEDIA_ROOT/'payment/recipe/'
        
        fs = FileSystemStorage(location=folder)        
        
        new_filename = order_number
        
        # Get the file extension from the original file name
        file_extension = os.path.splitext(image.name)[1]
        # file_extension = os.path.splitext(image)[1]
        
        # Concatenate the new file name and extension
        new_file_path = new_filename + file_extension
        
        # Save the uploaded file with the new file name
        filename = fs.save(new_file_path, image)
        
        # Generate the URL for accessing the uploaded file
        uploaded_file_url = fs.url('payment/recipe/' + filename)        
        payment = Payment(
            user = request.user, 
            order_id = order,
            recipe_image = uploaded_file_url)
        payment.save()
        # return HttpResponse('successpul payment')
        messages.success(request, "اطلاعات پرداخت ثبت شد.")
        return redirect('checkout:orders')
    else:
        orders = Order.objects.filter(user=request.user)
    return render(request, 'checkout/orders.html', {'orders': orders})    

login_required
def orders(request):
    orders = Order.objects.filter(user=request.user)
    return render(request, 'checkout/orders.html', {'orders': orders})

login_required
def cancel(request, order_id):
    order = get_object_or_404(Order, id = order_id)
    order.delete()
    # orders = Order.objects.filter(user=request.user, status='New')
    return redirect('checkout:orders')
    # return render(request, 'checkout/orders.html', {'orders': orders})



def upload_image(request, order_number):
    image = request.FILES['recipe']
    fs = FileSystemStorage()
    # Generate a new file name

    folder = settings.MEDIA_ROOT/'payment/recipe/'
    
    fs = FileSystemStorage(location=folder)        
    
    new_filename = order_number
    
    # Get the file extension from the original file name
    file_extension = os.path.splitext(image.name)[1]
    # file_extension = os.path.splitext(image)[1]
    
    # Concatenate the new file name and extension
    new_file_path = new_filename + file_extension
    
    # Save the uploaded file with the new file name
    filename = fs.save(new_file_path, image)
    
    # Generate the URL for accessing the uploaded file
    uploaded_file_url = fs.url(filename)

    return HttpResponse(uploaded_file_url)
    # return redirect('checkout:orders')
    #     return render(request, 'upload_image.html', {'uploaded_file_url': uploaded_file_url})
    # return render(request, 'upload_image.html')

templates/checkout/orders.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}


{% if orders %}
<section style="background-color: #eee;">
    <div class="container py-5">
        <div class="row d-flex justify-content-center mb-3">
            <div class="col-md-12 col-xl-10">
                {% for order in orders %}
                <div class="card shadow-0 border rounded-3 mb-2">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0">
                                <div class="bg-image hover-zoom ripple rounded ripple-surface">
                                    {% for item in order.items.all %}

                                    <p class=" mb-4 mb-md-0">

                                        <a href="{% url 'product:detail' item.product.slug %}" target="_blank"
                                            class="btn btn-sm btn-outline-success position-relative mb-3 mx-4 px-4 justify-items-between">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                fill="currentColor" class="bi bi-tags-fill" viewBox="0 0 16 16">
                                                <path
                                                    d="M2 2a1 1 0 0 1 1-1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 2 6.586V2zm3.5 4a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z" />
                                                <path
                                                    d="M1.293 7.793A1 1 0 0 1 1 7.086V2a1 1 0 0 0-1 1v4.586a1 1 0 0 0 .293.707l7 7a1 1 0 0 0 1.414 0l.043-.043-7.457-7.457z" />
                                            </svg> {{ item }}
                                            <span
                                                class="position-absolute top-0 start-100 translate-middle badge bg-danger">
                                                {{ item.quantity }} {{ item.product.unit }}
                                            </span>
                                        </a>

                                    </p>

                                    {% endfor %}
                                </div>
                            </div>
                            <div class="col-md-4 col-lg-6 col-xl-6">
                                <h5><span class="badge bg-secondary">شماره سفارش</span>{{ order.order_number }}</h5>
                                <hr>
                                <p class="text-truncate mb-4 mb-md-0">
                                    <span class="badge bg-secondary">وضعیت سفارش</span> 
                                    {% if order.status %}تایید شده {% else %}در حال بررسی{% endif %}
                                </p>
                                <hr>
                                <p class="text-truncate mb-4 mb-md-0">
                                    <span class="badge bg-secondary">آدرس</span>
                                    {{ order.state }},
                                    {{ order.city }},
                                    {{ order.shipping_address }}
                                </p>
                                <hr>
                                <p class="text-truncate mb-4 mb-md-0">
                                    <span class="badge bg-secondary">وضعیت پرداخت</span>
                                    {{ order.payment_set.get.get_status_display }}
                                </p>

                            </div>
                            <div class="col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start">
                                <form class="mb-4" action="{% url 'checkout:cancel' order.pk %}" method="post">
                                    {% csrf_token %}
                                    <div class="d-flex justify-content-between">
                                        <h4 class="mb-1 me-1">
                                            {{ order.total_amount }} <span class="text-danger h6">تومان</span>
                                        </h4>
                                        <button class="btn btn-sm btn-danger" type="submit">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                                                fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                                <path
                                                    d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z" />
                                            </svg>
                                        </button>
                                    </div>

                                </form>

                                <h6 class="text-success">شماره کارت: 5894631147435093</h6>
                                <h6 class="text-success"> بانک رفاه: سکینه شکوهیان </h6>
                                <div class="d-flex flex-column mt-4">

                                    <img src="{{order.payment_set.get.recipe_image}}" alt="" srcset="">

                                    <form class="d-grid" action="{% url 'checkout:payment' order.id %}" method="post"
                                        enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <label for="formFileSm" class="form-label"> رسید پرداخت</label>
                                        <input class="form-control form-control-sm" name="recipe" id="formFileSm"
                                            type="file" required>
                                        <input class="form-control form-control-sm" name="order_id"
                                            value="{{ order.pk }}" hidden type="text">
                                        <button type="submit" class="btn btn-primary btn-sm my-2">ارسال رسید پرداخت</a>
                                    </form>



                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% else %}
<div class="text-center m-4">
    <p class="h3"> سفارشات خالی است.</p>
    <a href="{% url 'admin:login' %}">
        <a href="{% url 'product:index' %}" class="btn btn-outline-success px-5 mt-5 rounded-pill"> افزودن به سبد خرید و ثبت سفارش </a>
    </a>
</div>

{% endif %}


{% comment %} <div class="container">
    <div class="cart p-5 m-4  bg-white" style="border-radius:10px">
        {% for order in orders %}
        <p>{{ order }}</p>
        <p>{{ order.total_amount }}</p>
        <p>{{ order.state }}, {{ order.city }}, {{ order.shipping_address }}, {{ order.zip_code }}</p>
        {% for item in order.items.all %}
        <span class="badge bg-success">{{ item }} [{{ item.quantity }}]</span>

        {% endfor %}
        <form action="" method="post">
            <input class="btn btn-danger" type="submit" value="پرداخت">
        </form>
        {% endfor %}
        <div class="cart-body">
            {{ order_id }}
            <h5 class="cart-title">پرداخت</h5>
            <hr>
            <form action="{% url 'checkout:payment'  %}" method="post">
                {% csrf_token %}
                {{ form.order_id }}
                <input type="text" value="{{order_id}}">
                {{ form.as_p }}
                <input class="btn btn-danger" type="submit" value="ارسال">
            </form>
        </div>
    </div>
</div> {% endcomment %}

{% endblock %}

templates/checkout/payment.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}


{% if orders %}
<section style="background-color: #eee;">
    <div class="container py-5">
        <div class="row d-flex justify-content-center mb-3">
            <div class="col-md-12 col-xl-10">
                {% for order in orders %}
                <div class="card shadow-0 border rounded-3 mb-2">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-lg-6 col-xl-6">
                                <h5>{{ order }}</h5>

                                <p class="text-truncate mb-4 mb-md-0">
                                    {{ order.status }}
                                </p>
                                <p class="text-truncate mb-4 mb-md-0">
                                    {{ order.state }}, {{ order.city }}, {{ order.shipping_address }}
                                </p>
                                {% for item in order.items.all %}

                                <p class="text-truncate mb-4 mb-md-0">


                                    <a href="" type="button"
                                        class="btn btn-sm btn-outline-success position-relative px-5 ">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                            fill="currentColor" class="bi bi-tags-fill" viewBox="0 0 16 16">
                                            <path
                                                d="M2 2a1 1 0 0 1 1-1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 2 6.586V2zm3.5 4a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z" />
                                            <path
                                                d="M1.293 7.793A1 1 0 0 1 1 7.086V2a1 1 0 0 0-1 1v4.586a1 1 0 0 0 .293.707l7 7a1 1 0 0 0 1.414 0l.043-.043-7.457-7.457z" />
                                        </svg> {{ item }}
                                        <span
                                            class="position-absolute top-50 start-100 translate-middle badge bg-success">
                                            {{ item.quantity }}
                                        </span>
                                    </a>
                                </p>

                                {% endfor %}
                            </div>
                            <div class="col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start">
                                <div class="d-flex flex-row align-items-center mb-1">
                                    <h4 class="mb-1 me-1">{{ order.total_amount }}</h4>
                                    <span class="text-danger"><s>$20.99</s></span>
                                </div>
                                <h6 class="text-success">ارسال رایگان</h6>
                                <div class="d-flex flex-column mt-4">
                                    <a href="" class="btn btn-primary btn-sm mb-2">مشاهده همه محصولات گروه</a>
                                    <a class="btn btn-sm btn-danger m-1" href="">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                            fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                            <path
                                                d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z" />
                                        </svg>
                                    </a>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% else %}
<div class="text-center m-4">
    <p class="h3">دسته‌بندی محصولات خالی است.</p>
    <a href="{% url 'admin:login' %}">
        <button class="btn btn-outline-success px-5 mt-5 rounded-pill"> ایجاد دسته‌بندی محصولات </button>
    </a>
</div>

{% endif %}


{% comment %} <div class="container">
    <div class="cart p-5 m-4  bg-white" style="border-radius:10px">
        {% for order in orders %}
        <p>{{ order }}</p>
        <p>{{ order.total_amount }}</p>
        <p>{{ order.state }}, {{ order.city }}, {{ order.shipping_address }}, {{ order.zip_code }}</p>
        {% for item in order.items.all %}
        <span class="badge bg-success">{{ item }} [{{ item.quantity }}]</span>

        {% endfor %}
        <form action="" method="post">
            <input class="btn btn-danger" type="submit" value="پرداخت">
        </form>
        {% endfor %}
        <div class="cart-body">
            {{ order_id }}
            <h5 class="cart-title">پرداخت</h5>
            <hr>
            <form action="{% url 'checkout:payment'  %}" method="post">
                {% csrf_token %}
                {{ form.order_id }}
                <input type="text" value="{{order_id}}">
                {{ form.as_p }}
                <input class="btn btn-danger" type="submit" value="ارسال">
            </form>
        </div>
    </div>
</div> {% endcomment %}

{% endblock %}